accelerator: gpu
gpus: -1
strategy: ddp
profiler: simple
max_epochs: 500
log_every_n_steps: 1
gradient_clip_val: 0.5
gradient_clip_algorithm: norm
num_sanity_val_steps: 1
#precision: 16-mixed #only use for A series GPU