data_dir: /Mounts/rbg-storage1/users/urop/qiangbo/data/confidence_data
cache_path: /Mounts/rbg-storage1/users/urop/qiangbo/data/confidence_cache
server_cache: /storage/boqiang/data_confidence
msms_bin: /Mounts/rbg-storage1/users/urop/qiangbo/bin/msms
linker_dict: dataset/linker_conf.pkl
esm_embeddings_path: placeholder

data_source: confidence
limit_complexes: 0
all_atoms: false
receptor_radius: 30
c_alpha_max_neighbors: 10
atom_radius: 5
atom_max_neighbors: 10
matching: false
max_lig_size: 100
remove_hs: true
num_conformers: 1


loader:
  batch_size: 10
  num_workers: 20
  pin_memory: true
  shuffle: true


#server_cache: /storage/boqiang/data_protac/new_cache