data_dir: /Mounts/rbg-storage1/users/urop/qiangbo/code/case_study/solved/process
cache_path: /Mounts/rbg-storage1/users/urop/qiangbo/code/case_study/solved/cache
server_cache: /Mounts/rbg-storage1/users/urop/qiangbo/code/case_study/solved/cache
msms_bin: /Mounts/rbg-storage1/users/urop/qiangbo/bin/msms
linker_dict: dataset/linker_conf.pkl
esm_embeddings_path: placeholder

data_source: protac
limit_complexes: 0
all_atoms: false
receptor_radius: 30
c_alpha_max_neighbors: 10
atom_radius: 5
atom_max_neighbors: 10
matching: false
max_lig_size: 100
remove_hs: true
num_conformers: 1


loader:
  batch_size: 12
  num_workers: 32
  pin_memory: true
  shuffle: true
  